#!/usr/bin/env bash

go_years=(2015 2024)
js_years=(2025)

function set_go_template () {
    filename="main.go"
    cmd=(go run)

read -r -d '' template << EOM
package main

import "github.com/lindeneg/aoc/cl"

func main() {
	example := cl.NewInput("example.in")
	cl.Example(
		cl.Ex[int]{
			Want: 42,
			Fn:   func() int { return puzzle(example, false) },
		},
		//		cl.Ex[int]{
		//			Want: 42,
		//			Fn:   func() int { return puzzle(example, true) },
		//		},
	)
	//	input := cl.NewInput("puzzle.in")
	//	cl.Puzzle(
	//		cl.Ex[int]{
	//			Want: 0,
	//			Fn:   func() int { return puzzle(input, false) },
	//		},
	//		cl.Ex[int]{
	//			Want: 0,
	//			Fn:   func() int { return puzzle(input, true) },
	//		},
	//	)
}

func puzzle(input cl.Input, _ bool) int {
	return 0
}
EOM
}

function set_js_template () {
    filename="index.ts"
    cmd=(npx -y tsx)
read -r -d '' template << EOM
import Day from "../day";

const day${day} = new Day(
    (data: string[], part) => {
        let answer = 0;
        return answer;
    },
    [null, null],
    [null, null]
).setPostTransform((transformed) => {
    return transformed;
});

(async () => {
    await day${day}.examples(1);
    //await day${day}.solve();
})();

EOM
}
